version: '3'

services:

  app-service:
    build: 
      context: ./
      dockerfile: ./app-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    environment: 
      DSN: "host=postgres port=5432 user=postgres password=password dbname=countries sslmode=disable timezone=UTC connect_timeout=5"

 

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: countries
    volumes:
      - ./db-data/postgres/:/var/lib/postgressql/data/
  
